# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/niek/Code/Goedemorgen

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/niek/Code/Goedemorgen

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/niek/Code/Goedemorgen/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/niek/Code/Goedemorgen/CMakeFiles /home/niek/Code/Goedemorgen/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/niek/Code/Goedemorgen/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named goedemorgen

# Build rule for target.
goedemorgen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 goedemorgen
.PHONY : goedemorgen

# fast build rule for target.
goedemorgen/fast:
	$(MAKE) -f CMakeFiles/goedemorgen.dir/build.make CMakeFiles/goedemorgen.dir/build
.PHONY : goedemorgen/fast

src/bronnen/Afval.o: src/bronnen/Afval.cpp.o

.PHONY : src/bronnen/Afval.o

# target to build an object file
src/bronnen/Afval.cpp.o:
	$(MAKE) -f CMakeFiles/goedemorgen.dir/build.make CMakeFiles/goedemorgen.dir/src/bronnen/Afval.cpp.o
.PHONY : src/bronnen/Afval.cpp.o

src/bronnen/Afval.i: src/bronnen/Afval.cpp.i

.PHONY : src/bronnen/Afval.i

# target to preprocess a source file
src/bronnen/Afval.cpp.i:
	$(MAKE) -f CMakeFiles/goedemorgen.dir/build.make CMakeFiles/goedemorgen.dir/src/bronnen/Afval.cpp.i
.PHONY : src/bronnen/Afval.cpp.i

src/bronnen/Afval.s: src/bronnen/Afval.cpp.s

.PHONY : src/bronnen/Afval.s

# target to generate assembly for a file
src/bronnen/Afval.cpp.s:
	$(MAKE) -f CMakeFiles/goedemorgen.dir/build.make CMakeFiles/goedemorgen.dir/src/bronnen/Afval.cpp.s
.PHONY : src/bronnen/Afval.cpp.s

src/bronnen/Bron.o: src/bronnen/Bron.cpp.o

.PHONY : src/bronnen/Bron.o

# target to build an object file
src/bronnen/Bron.cpp.o:
	$(MAKE) -f CMakeFiles/goedemorgen.dir/build.make CMakeFiles/goedemorgen.dir/src/bronnen/Bron.cpp.o
.PHONY : src/bronnen/Bron.cpp.o

src/bronnen/Bron.i: src/bronnen/Bron.cpp.i

.PHONY : src/bronnen/Bron.i

# target to preprocess a source file
src/bronnen/Bron.cpp.i:
	$(MAKE) -f CMakeFiles/goedemorgen.dir/build.make CMakeFiles/goedemorgen.dir/src/bronnen/Bron.cpp.i
.PHONY : src/bronnen/Bron.cpp.i

src/bronnen/Bron.s: src/bronnen/Bron.cpp.s

.PHONY : src/bronnen/Bron.s

# target to generate assembly for a file
src/bronnen/Bron.cpp.s:
	$(MAKE) -f CMakeFiles/goedemorgen.dir/build.make CMakeFiles/goedemorgen.dir/src/bronnen/Bron.cpp.s
.PHONY : src/bronnen/Bron.cpp.s

src/bronnen/Weer.o: src/bronnen/Weer.cpp.o

.PHONY : src/bronnen/Weer.o

# target to build an object file
src/bronnen/Weer.cpp.o:
	$(MAKE) -f CMakeFiles/goedemorgen.dir/build.make CMakeFiles/goedemorgen.dir/src/bronnen/Weer.cpp.o
.PHONY : src/bronnen/Weer.cpp.o

src/bronnen/Weer.i: src/bronnen/Weer.cpp.i

.PHONY : src/bronnen/Weer.i

# target to preprocess a source file
src/bronnen/Weer.cpp.i:
	$(MAKE) -f CMakeFiles/goedemorgen.dir/build.make CMakeFiles/goedemorgen.dir/src/bronnen/Weer.cpp.i
.PHONY : src/bronnen/Weer.cpp.i

src/bronnen/Weer.s: src/bronnen/Weer.cpp.s

.PHONY : src/bronnen/Weer.s

# target to generate assembly for a file
src/bronnen/Weer.cpp.s:
	$(MAKE) -f CMakeFiles/goedemorgen.dir/build.make CMakeFiles/goedemorgen.dir/src/bronnen/Weer.cpp.s
.PHONY : src/bronnen/Weer.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/goedemorgen.dir/build.make CMakeFiles/goedemorgen.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/goedemorgen.dir/build.make CMakeFiles/goedemorgen.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/goedemorgen.dir/build.make CMakeFiles/goedemorgen.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... package"
	@echo "... package_source"
	@echo "... goedemorgen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... src/bronnen/Afval.o"
	@echo "... src/bronnen/Afval.i"
	@echo "... src/bronnen/Afval.s"
	@echo "... src/bronnen/Bron.o"
	@echo "... src/bronnen/Bron.i"
	@echo "... src/bronnen/Bron.s"
	@echo "... src/bronnen/Weer.o"
	@echo "... src/bronnen/Weer.i"
	@echo "... src/bronnen/Weer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

